# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoCircleMenu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoCircleMenu
	pod 'ExpandingMenu', '~> 0.4'
end
